[package]
name = "svc-b"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
calimero-sdk = { path = "../../../../../../../crates/sdk" }
calimero-storage = { path = "../../../../../../../crates/storage" }

[build-dependencies]
calimero-wasm-abi = { path = "../../../../../../../crates/wasm-abi" }
serde_json = "1"
