//! A root collection that stores a single value.
//!
//! # CRDT trait surface
//!
//! `Root<T>` is the top-level state holder for an `#[app::state]` struct.
//! It is deliberately **not** itself a CRDT and implements **none** of
//! [`Mergeable`](super::crdt_meta::Mergeable),
//! [`CrdtMap`](super::crdt_meta::CrdtMap),
//! [`CrdtSequence`](super::crdt_meta::CrdtSequence), or
//! [`CrdtSet`](super::crdt_meta::CrdtSet). Root-state convergence happens at
//! a different layer: the merge dispatcher in `interface.rs` recognises the
//! root entry via `is_app_root_entry` and routes it through
//! `merge_root_state`, which delegates to the application's registered
//! field-by-field merge function (auto-generated by `#[app::state]`).
//!
//! Shape-wise `Root<T>` is a smart-pointer/wrapper (`Deref<Target = T>`),
//! not a keyed/indexed/membership collection, so none of the shape sub-traits
//! apply. The `Mergeable` blanket impls would also be unsound here: the
//! root entry must merge field-by-field via the app-registered merger, not
//! by delegating to any single inner `Mergeable::merge`.

use core::fmt;
use std::cell::RefCell;
use std::ops::{Deref, DerefMut};
use std::ptr;

use super::{Collection, ROOT_ENTRY_ID, ROOT_ID};
use crate::address::Id;
use crate::delta::{push_comparison, StorageDelta};
use crate::index::DeferredAncestorScope;
use crate::integration::Comparison;
use crate::interface::{Action, Interface, StorageError};
use crate::store::{MainStorage, StorageAdaptor};
use borsh::{from_slice, BorshDeserialize, BorshSerialize};
use tracing::info;

/// A set collection that stores unqiue values once.
pub struct Root<T, S: StorageAdaptor = MainStorage> {
    inner: Collection<T, S>,
    value: RefCell<Option<T>>,
    dirty: bool,
}

impl<T, S> fmt::Debug for Root<T, S>
where
    T: BorshSerialize + BorshDeserialize + fmt::Debug,
    S: StorageAdaptor,
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Root")
            .field("inner", &self.inner)
            .field("value", &self.value)
            .field("dirty", &self.dirty)
            .finish()
    }
}

impl<T> Root<T, MainStorage>
where
    T: BorshSerialize + BorshDeserialize,
{
    /// Creates a new root collection with the given value.
    pub fn new<F: FnOnce() -> T>(f: F) -> Self {
        Self::new_internal(f)
    }
}

impl<T, S> Root<T, S>
where
    T: BorshSerialize + BorshDeserialize,
    S: StorageAdaptor,
{
    /// Creates a new root collection with the given value.
    #[expect(clippy::expect_used, reason = "fatal error if it happens")]
    pub fn new_internal<F: FnOnce() -> T>(f: F) -> Self {
        let mut inner = Collection::new(Some(*ROOT_ID));

        let id = Self::entry_id();

        // `Root<T>`'s single entry carries `field_name = "root"` but no
        // `crdt_type`. The merge dispatch in `interface.rs` recognises
        // this id (via `is_app_root_entry`) and routes it through
        // `merge_root_state`, which delegates to the application's
        // registered `Mergeable` impl — auto-generated by `#[app::state]`
        // — so each field merges with its own CRDT semantics. A
        // bootstrap-aware default in `merge_root_state` covers the
        // never-explicitly-written case for apps without a registered
        // merger.
        //
        // The entry MUST NOT carry an `LwwRegister` `crdt_type`. Doing so
        // routes the whole `Root` blob through the built-in non-root
        // LWW-by-HLC path, which causes silent data loss in two cases:
        //   1) Bootstrap — a just-materialised local `Root` with a later
        //      HLC than an earlier-written remote `Root` wins LWW and
        //      drops all remote bytes (no-data-after-cold-join symptoms).
        //   2) Concurrent writes — whole-blob LWW silently drops one
        //      side's field-level CRDT contributions (violates the
        //      "no silent data loss" invariant).
        //
        // `field_name = "root"` is still set so peer-side
        // `compare_tree_nodes` keeps routing this leaf the same way it
        // always has — the only change is that `crdt_type` is `None`.
        //
        // SAFETY: `insert_with_field_name` only returns `Err` if the
        // underlying storage backend itself is in a fatal state (e.g.
        // a `StoreError` from a write to the host store). That is the
        // same precondition the rest of `Root::new_internal`'s panics
        // rely on — there is no recoverable failure mode here.
        let value = inner
            .insert_with_field_name(id, f(), "root")
            .expect("fatal: Root<T> entry insert failed");

        Self {
            inner,
            dirty: false,
            value: RefCell::new(Some(value)),
        }
    }

    /// The fixed id of the single entry under a `Root<T>` collection.
    ///
    /// Returns the module-level [`ROOT_ENTRY_ID`] constant so the value
    /// stays in lockstep with the merge-dispatch predicate
    /// (`is_app_root_entry`) that recognises this id in `interface.rs`.
    pub(crate) fn entry_id() -> Id {
        ROOT_ENTRY_ID
    }

    #[expect(clippy::mut_from_ref, reason = "'tis fine")]
    #[expect(clippy::unwrap_used, reason = "fatal error if it happens")]
    fn get(&self) -> &mut T {
        let mut value = self.value.borrow_mut();

        let id = Self::entry_id();

        let value = value.get_or_insert_with(|| self.inner.get(id).unwrap().unwrap());

        #[expect(unsafe_code, reason = "necessary for caching")]
        let value = unsafe { &mut *ptr::from_mut(value) };

        value
    }

    /// Fetches the root collection.
    #[expect(
        clippy::unwrap_used,
        clippy::unwrap_in_result,
        reason = "fatal error if it happens"
    )]
    pub fn fetch() -> Option<Self> {
        let inner = <Interface<S>>::root().unwrap()?;

        Some(Self {
            inner,
            dirty: false,
            value: RefCell::new(None),
        })
    }

    /// Commits the root collection.
    #[expect(clippy::unwrap_used, reason = "fatal error if it happens")]
    pub fn commit(mut self) {
        if self.dirty {
            if let Some(value) = self.value.into_inner() {
                if let Some(mut entry) = self.inner.get_mut(Self::entry_id()).unwrap() {
                    *entry = value;
                }
            }
        }

        <Interface<S>>::commit_root(Some(self.inner)).unwrap();
    }

    /// Commits the root collection without an instance of the root state.
    #[expect(
        clippy::panic,
        reason = "fatal error if it happens; tracing::error first so node logs \
                  carry the cause before the WASM abort, then panic with the \
                  Display form in the message for any panic-hook consumer"
    )]
    pub fn commit_headless() {
        <Interface<S>>::commit_root::<Collection<T>>(None).unwrap_or_else(|e| {
            tracing::error!(
                target: "storage::root",
                error = %e,
                "commit_headless: Interface::commit_root failed — panicking"
            );
            panic!("commit_headless: fatal: {e}");
        });
    }

    /// Syncs the root collection.
    ///
    /// `ctx` is the apply-time context for the inner [`Interface::apply_action`]
    /// calls. Per #2266, the [`StorageDelta::CausalActions`] variant
    /// carries pre-resolved `effective_writers` per Shared entity from
    /// the sync layer; this function builds a per-action `ApplyContext`
    /// from that map and ignores the passed `ctx` for that variant. For
    /// [`StorageDelta::Actions`] the passed `ctx` is used as-is (typically
    /// empty — verifier falls back to v2 stored-writers).
    ///
    /// Takes `&ApplyContext` (not by-value) for parity with
    /// [`Interface::apply_action`]; per #2272 review.
    #[expect(clippy::missing_errors_doc, reason = "NO")]
    pub fn sync(args: &[u8], ctx: &crate::interface::ApplyContext) -> Result<(), StorageError> {
        let artifact =
            from_slice::<StorageDelta>(args).map_err(StorageError::DeserializationError)?;

        let variant = match &artifact {
            StorageDelta::Actions(_) => "Actions",
            StorageDelta::CausalActions { .. } => "CausalActions",
            StorageDelta::Comparisons(_) => "Comparisons",
        };

        // `match` is an expression — assign directly. `inspect_err` then
        // logs without rewriting the Result; `?` propagates the Err to
        // the caller (the SDK macro's `.expect("fatal: sync failed")`).
        // Without this trace, a `Result::Err` from apply_actions surfaces
        // as a bare WASM `unreachable` trap with no clue what failed.
        match artifact {
            StorageDelta::Actions(actions) => Self::apply_actions(actions, |_| ctx.clone()),
            StorageDelta::CausalActions {
                actions,
                delta_id,
                delta_hlc,
                effective_writers,
            } => Self::apply_actions(actions, |action| crate::interface::ApplyContext {
                effective_writers: effective_writers.get(&action.id()).cloned(),
                delta_id: Some(delta_id),
                delta_hlc: Some(delta_hlc),
            }),
            // Extracted to a helper so the `?` operators inside
            // propagate to a Result that the match arm returns,
            // which then flows through the `.inspect_err()` below.
            // Inlining the body here would let the inner `?`
            // return from `sync` directly, bypassing the trace.
            StorageDelta::Comparisons(comparisons) => Self::apply_comparisons(comparisons, ctx),
        }
        .inspect_err(|e| {
            tracing::error!(
                target: "storage::root",
                variant,
                error = %e,
                "Root::sync returned Err — will bubble up to __calimero_sync_next's .expect()"
            );
        })?;

        info!(
            target: "storage::root",
            variant,
            "committing root after delta replay"
        );
        Self::commit_headless();

        Ok(())
    }

    /// Apply a batch of `Comparison` entries from a sync delta.
    ///
    /// Extracted to a helper so the inner `?` operators propagate to
    /// this function's `Result`, which the caller (`Self::sync`) returns
    /// from its match expression and then runs through `.inspect_err`.
    /// Inlining the body in the match arm would let `?` skip over the
    /// trace.
    fn apply_comparisons(
        comparisons: Vec<Comparison>,
        ctx: &crate::interface::ApplyContext,
    ) -> Result<(), StorageError> {
        if comparisons.is_empty() {
            push_comparison(Comparison {
                data: <Interface<S>>::find_by_id_raw(Id::root()),
                comparison_data: <Interface<S>>::generate_comparison_data(None)?,
            });
        }
        for Comparison {
            data,
            comparison_data,
        } in comparisons
        {
            <Interface<S>>::compare_affective(data, comparison_data, ctx)?;
        }
        Ok(())
    }

    /// Apply a batch of actions, deriving the per-action [`ApplyContext`]
    /// from `ctx_for_action`. Shared between the `Actions` (uniform ctx)
    /// and `CausalActions` (per-action ctx via `effective_writers` lookup)
    /// branches of [`Self::sync`].
    fn apply_actions<F>(actions: Vec<Action>, ctx_for_action: F) -> Result<(), StorageError>
    where
        F: Fn(&Action) -> crate::interface::ApplyContext,
    {
        let mut root_snapshot: Option<(Vec<u8>, crate::entities::Metadata)> = None;

        // #2238: defer ancestor-hash recomputation until the end of
        // the action loop. Many deltas in a single merge often touch
        // the same parent; without batching, each `add_child_to`
        // walks from that parent to the root redoing the same O(K)
        // hash work. The scope dedupes starting ids and flushes via
        // `finish()?` after the loop so storage errors during flush
        // propagate back to the caller (an error here means the
        // merkle tree is left inconsistent).
        let defer_scope = DeferredAncestorScope::<S>::new();

        for action in actions {
            match &action {
                Action::Add {
                    id, data, metadata, ..
                }
                | Action::Update {
                    id, data, metadata, ..
                } if id.is_root() => {
                    info!(
                        target: "storage::root",
                        payload_len = data.len(),
                        created_at = metadata.created_at,
                        updated_at = metadata.updated_at(),
                        "captured root snapshot from delta replay"
                    );
                    root_snapshot = Some((data.clone(), metadata.clone()));
                }
                _ => {}
            }

            let action_ctx = ctx_for_action(&action);

            match action {
                Action::Compare { id } => {
                    push_comparison(Comparison {
                        data: <Interface<S>>::find_by_id_raw(id),
                        comparison_data: <Interface<S>>::generate_comparison_data(Some(id))?,
                    });
                }
                Action::Add {
                    id,
                    data,
                    metadata,
                    ancestors,
                } => {
                    if !id.is_root() {
                        info!(
                            target: "storage::sync_child",
                            %id,
                            data_len = data.len(),
                            created_at = metadata.created_at,
                            updated_at = metadata.updated_at(),
                            "SYNC CHILD: Applying Action::Add for child entity"
                        );
                        <Interface<S>>::apply_action(
                            Action::Add {
                                id,
                                data,
                                metadata,
                                ancestors,
                            },
                            &action_ctx,
                        )?;
                    }
                }
                Action::Update {
                    id,
                    data,
                    metadata,
                    ancestors,
                } => {
                    if !id.is_root() {
                        info!(
                            target: "storage::sync_child",
                            %id,
                            data_len = data.len(),
                            created_at = metadata.created_at,
                            updated_at = metadata.updated_at(),
                            "SYNC CHILD: Applying Action::Update for child entity"
                        );
                        <Interface<S>>::apply_action(
                            Action::Update {
                                id,
                                data,
                                metadata,
                                ancestors,
                            },
                            &action_ctx,
                        )?;
                    }
                }
                Action::DeleteRef { .. } => {
                    <Interface<S>>::apply_action(action, &action_ctx)?;
                }
            };
        }

        // Flush deferred ancestor walks. Errors here indicate a
        // partially-propagated merkle tree and must surface to the
        // caller rather than being silently logged by Drop.
        defer_scope.finish()?;

        if let Some((payload, metadata)) = root_snapshot {
            if <Interface<S>>::save_raw(Id::root(), payload, metadata)?.is_some() {
                info!(
                    target: "storage::root",
                    "persisted root document from delta replay"
                );
            }
        }

        Ok(())
    }
}

impl<T, S> Deref for Root<T, S>
where
    T: BorshSerialize + BorshDeserialize,
    S: StorageAdaptor,
{
    type Target = T;

    fn deref(&self) -> &Self::Target {
        self.get()
    }
}

impl<T, S> DerefMut for Root<T, S>
where
    T: BorshSerialize + BorshDeserialize,
    S: StorageAdaptor,
{
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.dirty = true;

        self.get()
    }
}
