//! Convergence + correctness for the `#[derive(Mergeable)]` variant, driven
//! through the convergence harness. `TeamStats` gets its `RekeyTarget` impl
//! generated by the derive (no hand-written rekey) — confirming the #2577 fix
//! is automatic on the derive path.
//!
//! `#[serial]`: `converge_app` clears/repopulates the process-global merge
//! registry per run.

use calimero_storage::testing::converge_app;
use serial_test::serial;
use team_metrics_macro::TeamMetricsApp;

#[test]
#[serial]
fn team_stats_converge() {
    converge_app(TeamMetricsApp::init)
        .replicas(3)
        .ops(|s| {
            let _ = s.record_win("liverpool".into());
        })
        .ops(|s| {
            let _ = s.record_win("arsenal".into());
        })
        .assert_all_replicas_equal();
}

#[test]
#[serial]
fn team_stats_converge_to_correct_value() {
    // With #2577 merged + the derive-generated `RekeyTarget`, concurrent wins
    // SUM. Register the generated re-key thunks (WASM-load / bridge path).
    TeamMetricsApp::__calimero_register_rekey();

    converge_app(TeamMetricsApp::init)
        .replicas(3)
        .ops(|s| {
            let _ = s.record_win("liverpool".into());
        })
        .invariant("liverpool wins == 3 (one per replica)", |s| {
            s.get_wins("liverpool".into()).unwrap_or(0) == 3
        })
        .assert_all_replicas_equal();
}
