[package]
name = "state-schema-conformance"
description = "Calimero state schema conformance test application"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
calimero-sdk.workspace = true
calimero-storage.workspace = true

[package.metadata.workspaces]
independent = true

[package.metadata.calimero]
package = "com.calimero.state-schema-conformance"
name = "State Schema Conformance"
