[package]
name = "search-chat"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
calimero-primitives = { workspace = true, features = ["borsh"] }
calimero-sdk.workspace = true
calimero-storage.workspace = true

[dev-dependencies]
calimero-storage = { workspace = true, features = ["testing"] }

[package.metadata.calimero]
package = "com.calimero.search-chat"
name = "Search Chat (PoC)"

[package.metadata.workspaces]
independent = true
