//! Wire format — the one property that spans every type in the crate: what a
//! credential encodes to must decode back to the same value, or a peer reads a
//! different credential than the one that was signed.

use calimero_primitives::identity::{AccountId, DeviceId};

use super::support::{genesis_for, key, sign_cert, sign_handoff};
use crate::account::borsh_bytes;
use crate::account::AccountGenesis;
use crate::device::DeviceCert;
use crate::root_key::RootKeyHandoff;

#[test]
fn credentials_round_trip_through_borsh() {
    let (root, r1, dev) = (key(1), key(2), key(5));
    let g = genesis_for(&root);
    let account = g.account_id();
    let device = DeviceId::mint(account, [3u8; 16]);
    let handoff = sign_handoff(&root, account, 0, &r1);
    let cert = sign_cert(&root, account, device, &dev, 0, 0);

    for (label, bytes, ok) in [
        (
            "genesis",
            borsh_bytes(&g),
            borsh::from_slice::<AccountGenesis>(&borsh_bytes(&g)).map(|v| v == g),
        ),
        (
            "handoff",
            borsh_bytes(&handoff),
            borsh::from_slice::<RootKeyHandoff>(&borsh_bytes(&handoff)).map(|v| v == handoff),
        ),
        (
            "cert",
            borsh_bytes(&cert),
            borsh::from_slice::<DeviceCert>(&borsh_bytes(&cert)).map(|v| v == cert),
        ),
    ] {
        assert!(!bytes.is_empty(), "{label} encodes to nothing");
        assert_eq!(ok.ok(), Some(true), "{label} did not round-trip");
    }
}

#[test]
fn ids_round_trip_through_borsh() {
    let account = genesis_for(&key(1)).account_id();
    let device = DeviceId::mint(account, [3u8; 16]);
    assert_eq!(
        borsh::from_slice::<AccountId>(&borsh_bytes(&account)).expect("decode"),
        account
    );
    assert_eq!(
        borsh::from_slice::<DeviceId>(&borsh_bytes(&device)).expect("decode"),
        device
    );
}

/// Byte-for-byte encodings recorded **before** the credential types were reshaped
/// — the anchor, the handoff, both root-signed statements, and the two
/// `AccountProof` bundles that replaced `JoinAccountCredential` and the old
/// hand-rolled `SignedDeviceRevocation` struct.
///
/// Round-tripping only proves this build agrees with itself. These pin it to the
/// build before, which is the property that actually matters: a join op and a
/// revocation proof are on the wire and in stored ops, so a field reordered or a
/// bundle re-nested during a refactor would be read as a *different credential*
/// by every peer that had not upgraded. Generated by encoding the fixtures below
/// on the pre-refactor tree; if one of these fails, the encoding moved and that is
/// a wire break needing a version bump, not a test to update.
mod recorded_before_the_refactor {
    use borsh::to_vec;
    use calimero_primitives::identity::{DeviceId, PrivateKey};

    use crate::account::AccountGenesis;
    use crate::device::{DeviceCert, KemPublicKey};
    use crate::revocation::DeviceRevocation;
    use crate::root_key::RootKeyHandoff;
    use crate::signed::AccountProof;

    const GENESIS: &str = "028a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c";
    const HANDOFF: &str = "04cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b0000000008139770ea87d175f56a35466c34c7ecccb8d8a91b4ee37a25df60f5b8fc9b39413b4e37f05d61bed2409074f3e070a83d6f4482d4b526cca5adcd694dd572d83fb308a9d29d52bc17d4ee47935fadf42e267770ab97e168a370a38c784466f08";
    const CERT: &str = "04cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b095c18ffae8a7c7c574f96d8330403377f9e699e8958573846a4d73ced987d65f6e7a1cdd29b0b78fd13af4c5598feff4ef2a97166e3ca6f2e4fbfccd80505bf10909090909090909090909090909090909090909090909090909090909090909000000000000000025181b9e3f23b28442300db328ac443f522c40cc1387bb60ea9ff9ff22bc0003c1cfc938d700c839df21920eff48ed454cc00b97f10c69dbb06055c12f98ef09";
    const REVOCATION: &str = "04cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b095c18ffae8a7c7c574f96d8330403377f9e699e8958573846a4d73ced987d65f0000000010ff27d8a169b33c77c419b3abc864cbbf8e9f5e72f561787d95046ff383901fdc702b499032186e5a6d958d804b4e337f6cc21c3fbd9b90051f90e9c7798504";
    const CERT_PROOF: &str = "028a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c0100000004cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b0000000008139770ea87d175f56a35466c34c7ecccb8d8a91b4ee37a25df60f5b8fc9b39413b4e37f05d61bed2409074f3e070a83d6f4482d4b526cca5adcd694dd572d83fb308a9d29d52bc17d4ee47935fadf42e267770ab97e168a370a38c784466f0804cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b095c18ffae8a7c7c574f96d8330403377f9e699e8958573846a4d73ced987d65f6e7a1cdd29b0b78fd13af4c5598feff4ef2a97166e3ca6f2e4fbfccd80505bf10909090909090909090909090909090909090909090909090909090909090909000000000000000025181b9e3f23b28442300db328ac443f522c40cc1387bb60ea9ff9ff22bc0003c1cfc938d700c839df21920eff48ed454cc00b97f10c69dbb06055c12f98ef09";
    const REVOCATION_PROOF: &str = "028a88e3dd7409f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c0100000004cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b0000000008139770ea87d175f56a35466c34c7ecccb8d8a91b4ee37a25df60f5b8fc9b39413b4e37f05d61bed2409074f3e070a83d6f4482d4b526cca5adcd694dd572d83fb308a9d29d52bc17d4ee47935fadf42e267770ab97e168a370a38c784466f0804cfa21629a77f8cd8ddd3f821ed514009a9f572b2ce8e0a11f5cbb5e25340b095c18ffae8a7c7c574f96d8330403377f9e699e8958573846a4d73ced987d65f0000000010ff27d8a169b33c77c419b3abc864cbbf8e9f5e72f561787d95046ff383901fdc702b499032186e5a6d958d804b4e337f6cc21c3fbd9b90051f90e9c7798504";

    #[test]
    fn every_credential_encodes_to_the_bytes_it_always_did() {
        let (root, next, dev) = (
            PrivateKey::from([1u8; 32]),
            PrivateKey::from([2u8; 32]),
            PrivateKey::from([5u8; 32]),
        );
        let genesis = AccountGenesis::new(root.public_key());
        let account = genesis.account_id();
        let device = DeviceId::mint(account, [3u8; 16]);
        let kem = KemPublicKey::from([9u8; 32]);

        let handoff =
            RootKeyHandoff::sign(&root, account, 0, &next.public_key()).expect("sign handoff");
        let cert = DeviceCert::sign(&root, account, device, &dev.public_key(), &kem, 0, 0)
            .expect("sign cert");
        let revocation =
            DeviceRevocation::sign(&root, account, device, 0).expect("sign revocation");

        let cert_proof = AccountProof {
            genesis,
            chain: vec![handoff],
            statement: cert,
        };
        let revocation_proof = AccountProof {
            genesis,
            chain: vec![handoff],
            statement: revocation,
        };

        for (label, expected, actual) in [
            ("genesis", GENESIS, to_vec(&genesis).expect("encode")),
            ("handoff", HANDOFF, to_vec(&handoff).expect("encode")),
            ("cert", CERT, to_vec(&cert).expect("encode")),
            (
                "revocation",
                REVOCATION,
                to_vec(&revocation).expect("encode"),
            ),
            (
                "cert proof",
                CERT_PROOF,
                to_vec(&cert_proof).expect("encode"),
            ),
            (
                "revocation proof",
                REVOCATION_PROOF,
                to_vec(&revocation_proof).expect("encode"),
            ),
        ] {
            assert_eq!(
                hex::encode(&actual),
                expected,
                "{label} no longer encodes to the bytes peers expect"
            );
        }
    }
}
