//! A GNU sparse entry's holes are generated by `tar`, not read from the capped stream.

use std::collections::BTreeSet;
use std::io;

use flate2::read::GzDecoder;
use flate2::write::GzEncoder;
use flate2::Compression;
use tar::{Archive, Builder, EntryType, Header};

use super::extract_bundle_files;

const ARTIFACT: &str = "app.wasm";
const HOLE: u64 = 256 * 1024 * 1024; // declared real size, backed by zero archive bytes

/// One sparse entry at `ARTIFACT`: a single hole of `HOLE` bytes and no data.
fn sparse_bundle() -> Vec<u8> {
    let mut header = Header::new_gnu();
    header.set_path(ARTIFACT).unwrap();
    header.set_entry_type(EntryType::GNUSparse);
    header.set_mode(0o644);
    header.set_size(0);
    let gnu = header.as_gnu_mut().unwrap();
    gnu.set_real_size(HOLE);
    gnu.sparse[0].set_offset(HOLE);
    gnu.sparse[0].set_length(0);
    header.set_cksum();

    let mut tar = Builder::new(GzEncoder::new(Vec::new(), Compression::default()));
    tar.append(&header, io::empty()).unwrap();
    tar.into_inner().unwrap().finish().unwrap()
}

#[test]
fn a_sparse_entry_cannot_expand_past_what_the_archive_holds() {
    let bundle = sparse_bundle();

    let mut archive = Archive::new(GzDecoder::new(&bundle[..]));
    let mut entry = archive.entries().unwrap().next().unwrap().unwrap();
    assert_eq!(entry.header().entry_type(), EntryType::GNUSparse);
    assert_eq!(
        io::copy(&mut entry, &mut io::sink()).unwrap(),
        HOLE,
        "control: tar itself expands the {}-byte archive to the declared hole",
        bundle.len()
    );

    let extracted = extract_bundle_files(&bundle, &BTreeSet::from([ARTIFACT]));
    let expanded = extracted
        .as_ref()
        .ok()
        .and_then(|found| found.get(ARTIFACT))
        .map(|bytes| bytes.len());
    assert!(
        extracted.is_err() || expanded.is_none(),
        "a {}-byte bundle yielded a {expanded:?}-byte artifact",
        bundle.len()
    );
}
