name: Close Stale Issues & Pull Requests

on:
  schedule:
    - cron: "0 14 * * *" # Run every day at 2PM
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v11.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 180
          days-before-pr-stale: 7
          days-before-close: 7

          # --- Issues ---
          stale-issue-message: >
            This issue has been automatically marked as stale.
            **If this issue is still affecting you, please leave any comment** (for example, "bump"), and we'll keep it open.
            We are sorry that we haven't been able to prioritize it yet. If you have any new additional information, please include it with your comment!
          close-issue-message: >
            "This issue has been automatically closed because it has been
            inactive for more than 180 days. Please reopen and prioritize this for development if it is
            essential."
          exempt-issue-labels: "internal,bug, discussion,💎 bounty 💎, good first issue, epic, enhancement, improvement, question"

          # --- PRs ---
          stale-pr-label: "Stale"
          stale-pr-message: >
            This pull request has been automatically marked as stale.
            **If this pull request is still relevant, please leave any comment** (for example, "bump"), and we'll keep it open.
            We are sorry that we haven't been able to prioritize reviewing it yet. Your contribution is very much appreciated.
          close-pr-message: >
            "This pull request has been automatically closed because it has been
            inactive for more than 7 days. Please reopen and see this PR through its review if it is
            essential."
          exempt-pr-labels: "bug,discussion,💎 bounty 💎, epic, enhancement, improvement, needs investigation"
